import re
import pdfplumber
from pathlib import Path
import os

class PDFSkillExtractor:
    def __init__(self):
        # Anchor terms typically found in official LinkedIn PDF exports
        self.section_headers = [
            r"^Summary$",
            r"^Experience$",
            r"^Education$",
            r"^Licenses\s*&\s*Certifications$",
            r"^Top Skills$",
            r"^Languages$"
        ]
        self.header_pattern = re.compile(
            r"|".join(self.section_headers),
            re.IGNORECASE
        )

    def extract_text_from_pdf(self, pdf_path: str) -> str:
        """
        Extracts text by parsing layout blocks vertically to preserve two-column structures.
        """
        try:
            if not os.path.exists(pdf_path):
                raise FileNotFoundError(f"LinkedIn PDF file not found at: {pdf_path}")

            full_text = []

            with pdfplumber.open(pdf_path) as pdf:
                for page in pdf.pages: # full_text = [page.extract_text() for page in pdf.pages if page.extract_text(layout=True)]
                    # layout=True forces pdfplumber to respect visual columns and spacing
                    text = page.extract_text(layout=True)
                    if text:
                        full_text.append(text)

            return "\n".join(full_text)

        except Exception as e:
            print(f"❌ Failed to parse physical PDF file layout: {e}")
            return ""

    def parse_skills_section(self, raw_text: str) -> list[str]:
        """Organizes the parsed text blocks into individual profile categories."""
        lines = raw_text.split("\n")
        profile_data = {}
        current_section = "Contact/Header Info"
        current_content = []

        for line in lines:
            clean_line = line.strip()
            if not clean_line:
                continue

            # Skip header pagination strings generated by LinkedIn exports
            if "Page " in clean_line and " of " in clean_line:
                continue
            if re.match(r"^[-_]{2,}$", clean_line):
                continue
            # Match section changes
            if self.header_pattern.match(clean_line):
                if current_content:
                    profile_data[current_section] = "\n".join(current_content).strip()
                current_section = clean_line.title()
                current_content = []
            else:
                current_content.append(clean_line)

        # Catch the final section
        if current_content:
            profile_data[current_section] = "\n".join(current_content).strip()

        return profile_data


if __name__=="__main__":
    pdf_extractor = PDFSkillExtractor()

    root_dir = Path(__file__).resolve().parent
    if (root_dir / "resources").exists():
        project_root = root_dir
    else:
        project_root = root_dir.parent

    output_dir = project_root / "resources"
    pdf_path = output_dir / "linkedin_profile.pdf"

    print(f"📄 Parsing local LinkedIn PDF profile data: {pdf_path.name}...")
    print(f"📄 Looking for LinkedIn PDF at: {pdf_path.absolute()}")

    try:
        print(f"🔄 Parsing LinkedIn structural PDF: '{pdf_path}'...")
        raw_text = pdf_extractor.extract_text_from_pdf(pdf_path)
        parsed_profile = pdf_extractor.parse_skills_section(raw_text)

        print("\n✅ Extraction successful! Found sections:")
        for section, content in parsed_profile.items():

            print(f"🔹 {section} ({len(content.splitlines())} lines of data)")

        linkedin_skills_text = parsed_profile.get("Top Skills", "")
        header_block = parsed_profile.get("Contact/Header Info", "")
        header_lines = [line.strip() for line in header_block.split("\n") if line.strip()]

        current_role_guess = header_lines[1] if len(header_lines) > 1 else "Full Stack Developer"

        print(f"LinkedIn Skills {linkedin_skills_text}")
        print(f"Current Skills {current_role_guess}")

    except FileNotFoundError as e:
        print(f"⚠️ Simulation Mode: {e}")
        print("Rename your exported file to 'Profile.pdf' in this folder to run the live test.")